### ISSUE TITLE
在rk3566遇到Invalid RKNN model version 6的问题

### ISSUE THREAD

**Issue by jumengbo** [cqu20160901/yolov10_rknn_Cplusplus#4]
(toolkit_lite2_py3.8) cat@lubancat:~/Desktop/lubancat_ai_manual_code/dev_env/rknpu2/examples/yolov10_rknn_Cplusplus/install/rknn_yolov10_demo_Linux$ ./rknn_yolov10_demo 
Read /home/cat/Desktop/lubancat_ai_manual_code/dev_env/rknpu2/examples/yolov10_rknn_Cplusplus/test.jpg ...
img width = 640, img height = 640
E RKNN: [15:05:56.856] 6, 4
E RKNN: [15:05:56.856] Invalid RKNN model version 6
E RKNN: [15:05:56.856] rknn_init, load model failed!
rknn_init error ret=-6

**Comment by jumengbo** [comment]
已解决

**Comment by Yhc-777** [comment]
@cqu20160901 @jumengbo 你好，请问这个问题怎么解决的呢？我在转换rk3588的时候也遇到了这个问题。求解答
![image](https://github.com/user-attachments/assets/2a2eb170-aeee-46cb-9fdb-5af24a560043)

**Comment by jumengbo** [comment]
> @cqu20160901 @jumengbo 你好，请问这个问题怎么解决的呢？我在转换rk3588的时候也遇到了这个问题。求解答 ![image](https://private-user-images.githubusercontent.com/96092199/396405981-2a2eb170-aeee-46cb-9fdb-5af24a560043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjI2MDMsIm5iZiI6MTczNDQyMjMwMywicGF0aCI6Ii85NjA5MjE5OS8zOTY0MDU5ODEtMmEyZWIxNzAtYWVlZS00NmNiLTlmZGItNWFmMjRhNTYwMDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3NTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MDBjY2ZiN2ZkZjc2OGVmMjI3MjNlZjQ3MjMyYWIzOTZlNTEzMzZiYzc0NGVjNDk2ZDExMGY3NzNjZTVmMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ehzErjIN7ZGdZptq5luATrmEP1Z0CxTlvGOLGEP9hWk)
版本问题，将lib库换成自己版本的，在yolov10_rknn_Cplusplus/install/rknn_yolov10_demo_Linux/lib

**Comment by Yhc-777** [comment]
> > @cqu20160901 @jumengbo 你好，请问这个问题怎么解决的呢？我在转换rk3588的时候也遇到了这个问题。求解答 ![image](https://private-user-images.githubusercontent.com/96092199/396405981-2a2eb170-aeee-46cb-9fdb-5af24a560043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjI2MDMsIm5iZiI6MTczNDQyMjMwMywicGF0aCI6Ii85NjA5MjE5OS8zOTY0MDU5ODEtMmEyZWIxNzAtYWVlZS00NmNiLTlmZGItNWFmMjRhNTYwMDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3NTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MDBjY2ZiN2ZkZjc2OGVmMjI3MjNlZjQ3MjMyYWIzOTZlNTEzMzZiYzc0NGVjNDk2ZDExMGY3NzNjZTVmMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ehzErjIN7ZGdZptq5luATrmEP1Z0CxTlvGOLGEP9hWk)
> > 版本问题，将lib库换成自己版本的，在yolov10_rknn_Cplusplus/install/rknn_yolov10_demo_Linux/lib

@jumengbo 多谢指导，我修改后出现以下界面，请问是成功了吗？可是我没有看到相关的输出。
![image](https://github.com/user-attachments/assets/9a742637-653b-4728-97e5-d22039c360ba)

**Comment by cqu20160901** [comment]
rga resize的输入要支持16字节对齐，输入的宽1912不是16的倍数
